
#define GPIO_CONFIGURATION_PIN_13_MODE 2
#define GPIO_CONFIGURATION_PIN_13_INVERT 1

#define GPIO_CONFIGURATION_PIN_14_MODE 2
#define GPIO_CONFIGURATION_PIN_14_INVERT 1

#define GPIO_CONFIGURATION_PIN_15_MODE 2
#define GPIO_CONFIGURATION_PIN_15_INVERT 1

#define GPIO_CONFIGURATION_PIN_16_MODE 2
#define GPIO_CONFIGURATION_PIN_16_INVERT 1

#define GPIO_CONFIGURATION_PIN_11_MODE 1
#define GPIO_CONFIGURATION_PIN_11_PULL 1
#define GPIO_CONFIGURATION_PIN_11_INVERT 1

#define GPIO_CONFIGURATION_PIN_12_MODE 1
#define GPIO_CONFIGURATION_PIN_12_PULL 1
#define GPIO_CONFIGURATION_PIN_12_INVERT 1

#define GPIO_CONFIGURATION_PIN_24_MODE 1
#define GPIO_CONFIGURATION_PIN_24_PULL 1
#define GPIO_CONFIGURATION_PIN_24_INVERT 1

#define GPIO_CONFIGURATION_PIN_25_MODE 1
#define GPIO_CONFIGURATION_PIN_25_PULL 1
#define GPIO_CONFIGURATION_PIN_25_INVERT 1
