name: Reusable build workflow

on: 
  workflow_call:
    inputs:
      chip:
        required: true
        type: string
      publish_hex_no_crystal:
        required: false
        type: boolean
        default: true
      publish_hex_crystal:
        required: false
        type: boolean
        default: true
      publish_zip_no_crystal:
        required: false
        type: boolean
        default: true
      publish_zip_no_crystal_with_sd:
        required: false
        type: boolean
        default: true
      publish_zip_crystal:
        required: false
        type: boolean
        default: true
      publish_zip_crystal_with_sd:
        required: false
        type: boolean
        default: true
      publish_uf2:
        required: false
        type: boolean
        default: true
      board:
        required: false
        type: string
        default: generic

jobs:
  build:
    runs-on: [self-hosted, firmware-builder]
    env:
      CHIP: ${{ inputs.chip }}
      BLE_ROOT: ../../../../
      BOARD: ${{ inputs.board }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: parse feature template
      uses: cuchi/jinja2-action@v1.2.2
      with:
        template: src/config/feature_config.template.h.jinja
        output_file: src/config/feature_config.template.h

    - name: set PATH
      run: echo "../../../../" >> $GITHUB_PATH

    - name: build firmware zip (no crystal)
      if: ${{ inputs.publish_zip_no_crystal }}
      run: make sign
      env:
        LFCLK_SRC_XTAL: 0

    - name: build firmware hex (no crystal)
      if: ${{ inputs.publish_hex_no_crystal }}
      run: make hex
      env:
        LFCLK_SRC_XTAL: 0

    - name: build firmware + SD zip (no crystal)
      if: ${{ inputs.publish_zip_no_crystal_with_sd }}
      run: make sign_sd
      env:
        LFCLK_SRC_XTAL: 0

    - name: build firmware zip (crystal)
      if: ${{ inputs.publish_zip_crystal }}
      run: make sign
      env:
        LFCLK_SRC_XTAL: 1

    - name: build firmware hex (crystal)
      if: ${{ inputs.publish_hex_crystal }}
      run: make hex
      env:
        LFCLK_SRC_XTAL: 1

    - name: Download uf2conv.py
      if: ${{ inputs.publish_uf2 }}
      run: |
        wget https://raw.githubusercontent.com/microsoft/uf2/refs/heads/master/utils/uf2families.json
        wget https://raw.githubusercontent.com/microsoft/uf2/refs/heads/master/utils/uf2conv.py

    - name: Create uf2 file
      if: ${{ inputs.publish_uf2 }}
      run: |
        make uf2
      env:
        LFCLK_SRC_XTAL: 1

    - name: build firmware + SD (crystal)
      if: ${{ inputs.publish_zip_crystal_with_sd }}
      run: make sign_sd
      env:
        LFCLK_SRC_XTAL: 1

    - name: Upload firmwares to latest release
      uses: svenstaro/upload-release-action@2.7.0
      with:
        file: BLEnky*
        file_glob: true
        overwrite: true