name: Automated firmware test

on: [workflow_dispatch, push]

concurrency:
  group: firmware-test

jobs:
  build:
    runs-on: [self-hosted, firmware-builder]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: parse feature template
      uses: cuchi/jinja2-action@v1.2.2
      with:
        template: src/config/feature_config.template.h.jinja
        output_file: src/config/feature_config.template.h
    - name: build firmware
      run: |
        make BLE_ROOT=../../../../ FAMILY=NRF51
    - name: store firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware-file
        path: _build/nrf51822_xxac.hex

  flash:
    runs-on: [self-hosted, firmware-flasher]
    needs: build

    steps:
    - name: delete old firmware
      run: rm -f /home/home/ram/nrf51822_xxac.hex
    - name: download firmware
      uses: actions/download-artifact@v4
      with:
        name: firmware-file
        path: /home/home/ram/
    - name: flash firmware
      run: echo -e "program /home/home/ram/nrf51822_xxac.hex verify; program /home/home/Projects/BLEnky/testing/settings.hex verify reset \n exit" | nc localhost 4444

  test:
    runs-on: [self-hosted, firmware-flasher]
    needs: flash

    steps:
    - uses: actions/checkout@v4
      with:
        repository: dakhnod/BLEnky-testing-kit
        submodules: true
        path: testing-kit
    - name: run test script
      run: python -u main.py -a "F2:B4:78:83:18:E1" -o 6 13 19 26 -i 12 16 20 21
      working-directory: testing-kit
