name: Automated firmware build for release

on:
  release:
    types: [released, prereleased]

jobs:
  build_nrf51822:
    uses: ./.github/workflows/build.yml
    with:
      chip: NRF51822

  build_nrf52832:
    uses: ./.github/workflows/build.yml
    with:
      chip: NRF52832
      uf2_identifier: '0x72721d4e'

  build_nrf52840:
    uses: ./.github/workflows/build.yml
    with:
      chip: NRF52840
      uf2_identifier: '0xada52840'