name: Automated firmware build for release

on:
  release:
    types: [released, prereleased]

jobs:
  build_nrf51822:
    uses: ./.github/workflows/build.yml
    with:
      chip: NRF51822

  build_nrf52832:
    uses: ./.github/workflows/build.yml
    with:
      chip: NRF52832

  build_nrf52840:
    uses: ./.github/workflows/build.yml
    with:
      chip: NRF52840

  build_nrf21540-DK:
    uses: ./.github/workflows/build.yml
    with:
      chip: NRF52840
      publish_hex_no_crystal: false
      publish_hex_crystal: true
      publish_zip_no_crystal: false
      publish_zip_no_crystal_with_sd: false
      publish_zip_crystal: false
      publish_zip_crystal_with_sd: false
      publish_uf2: false
      board: nRF21540-DK